####################
#     cFoodRel     #
####################
#这里为你给要自定义的食物起的代号
text:
  #你食物的名字，要生效的食物必须与此名字一致
  name: '&c&l测试'
  #使用该物品需要的权限，默认为none
  Permission: none
  #是否使用OP权限执行绑定的指令
  op: true
  #绑定的指令，可多条
  cmd:
    - 'say Hello!'